### ISSUE TITLE
TypeScript is not compiled into dependencies

### ISSUE THREAD

**Issue by The2Alert** [nickolascarlos/class-validator-errors-flattener#2]
<code>class-validator-errors-flattener</code> is installed as the developer version.

![Screenshot_1](https://user-images.githubusercontent.com/68344264/166101435-e2f5bc60-acd0-4eee-8795-bd72cbe00368.png)

**Comment by nickolascarlos** [comment]
@dev2alert Thanks for pointing it out. I'm fixing it as soon as possible.
